### ISSUE TITLE
When mutating image name to image digest, annotate the original image name

### ISSUE THREAD

**Issue by wjwilson-ibm** [IBM/portieris#169] opened 2020-08-21 12:35 UTC
### What commit ID of Portieris did you experience the problem with?
August 19, 2020 - commit 850f87db866a4ab8816ebecadc66c52b8c6ec6fa

### What went wrong?
The image name is mutated to the image digest which loses the original image name.

### What should have happened differently?
The original image name should be recorded as an annotation in the deployment.

### How can it be reproduced?
- Sign an image with a name/version like "myimage:1.2".  
- Establish the k8s imagepolicy to require signing for myimages.  
- Edit the now mutated deployment and view the container "image" tag.  
- Search the deployment for the original image name.  It cannot be found.

**Comment by brackendawson** [comment] 2021-01-04 14:40
This looks like a duplicate of #114

**Comment by molepigeon** [comment] 2021-01-04 14:43
Agreed, closing in favour of #114

**Closed by molepigeon** 2021-01-04 14:43 UTC
